# Generated by Django 3.0.8 on 2020-07-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
